# Generated by Django 4.2.2 on 2023-12-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
